name: daily-build-validator

on:
  schedule:
    - cron: '55 19 * * *'    # 01:25 in LK time (GMT+5:30)
  workflow_dispatch:

jobs:
  build:
     uses: ./.github/workflows/daily-build-executor.yml
     secrets: inherit
     with:
      working_dir: validator
